# Generated by Django 5.1.3 on 2024-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='analyst',
            field=models.CharField(choices=[('Hassan', 'Hassan'), ('Arnold', 'Arnold'), ('João', 'João')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.CharField(choices=[('Comercial', 'Comercial'), ('Suporte', 'Suporte'), ('Financeiro', 'Financeiro')], max_length=100),
        ),
    ]
