# Generated by Django 5.1.3 on 2024-12-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_analyst_alter_ticket_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='analyst',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.CharField(max_length=50),
        ),
    ]
