# Generated by Django 5.1.3 on 2024-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='analyst',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sector',
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_analyst',
            field=models.CharField(blank=True, default='Sem Analista', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Título Padrão', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('atendendo', 'Atendendo'), ('encerrado', 'Encerrado'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
    ]
